services:
    django:
        build:
            context: ./backend
        command: sh scripts/init-db.sh
        container_name: django
        volumes:
            - ./backend:/app
        ports:
            - '8000:8000'
        env_file:
            - .env
        depends_on:
            - db
            - redis

    celery-worker-scraping:
        build:
            context: ./backend
        container_name: celery-worker-scraping
        command: celery -A core worker -l WARNING -Q scraping
        volumes:
            - ./backend:/app
        env_file:
            - .env
        depends_on:
            - django
            - redis

    celery-worker-database:
        build:
            context: ./backend
        container_name: celery-worker-database
        command: celery -A core worker -l WARNING -Q database
        volumes:
            - ./backend:/app
        env_file:
            - .env
        depends_on:
            - django
            - redis

    celery-beat:
        build:
            context: ./backend
        container_name: celery-beat
        command: celery -A core beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
        volumes:
            - ./backend:/app
        env_file:
            - .env
        depends_on:
            - django
            - redis

    redis:
        image: redis:7
        container_name: redis
        ports:
            - '6379:6379'

    db:
        image: postgres:15
        container_name: postgres
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        env_file:
            - .env

volumes:
    pgdata:
