services:
    redis:
        image: redis:7
        container_name: redis
        ports:
            - '6379:6379'

    scrapy:
        build: .
        container_name: scrapy
        working_dir: /app
        command: ['scrapy', 'crawl', 'schedule', '-a', 'leagues=nba']
        depends_on:
            - redis
        env_file: .env
