SPORTSBOOKS = [ 'fanduel', 'draftkings', 'betmgm', 'bet365', 'espnbet', 'caesars', 'fanatics', 'betrivers', ]

SPORTS = [ 'football', 'basketball', 'baseball', 'soccer', 'hockey', ]

LEAGUES = [ 'nfl', 'nba', 'mlb', 'mls', 'nhl', 'ncaaf', 'ncaab', 'ncaaw', ]

SPORTS_LEAGUES = {
    'football': ['nfl', 'ncaaf',],
    'basketball': ['nba', 'ncaab', 'ncaaw',],
    'baseball': ['mlb',],
    'soccer': ['mlb'],
    'hockey': ['nhl',],
}

SCHEDULE_URLS = {
    'nba': 'https://www.espn.com/nba/schedule',
    'mlb': 'https://www.espn.com/nba/schedule',
    'nfl': '',
    'ncaaf': '',
    'ncaab': '',
}

SPORTSBOOK_URLS = {
    'fanduel': '', 
    'draftkings': '',
    'betmgm': '',
    'bet365': '', 
    'espnbet': '',
}

NFL_ALIASES = {
    'arizona-cardinals': ['ARI', 'Arizona', 'Cardinals', 'Arizona Cardinals'],
    'atlanta-falcons': ['ATL', 'Atlanta', 'Falcons', 'Atlanta Falcons'],
    'baltimore-ravens': ['BAL', 'Baltimore', 'Ravens', 'Baltimore Ravens'],
    'buffalo-bills': ['BUF', 'Buffalo', 'Bills', 'Buffalo Bills'],
    'carolina-panthers': ['CAR', 'Carolina', 'Panthers', 'Carolina Panthers'],
    'chicago-bears': ['CHI', 'Chicago', 'Bears', 'Chicago Bears'],
    'cincinnati-bengals': ['CIN', 'Cincinnati', 'Bengals', 'Cincinnati Bengals'],
    'cleveland-browns': ['CLE', 'Cleveland', 'Browns', 'Cleveland Browns'],
    'dallas-cowboys': ['DAL', 'Dallas', 'Cowboys', 'Dallas Cowboys'],
    'denver-broncos': ['DEN', 'Denver', 'Broncos', 'Denver Broncos'],
    'detroit-lions': ['DET', 'Detroit', 'Lions', 'Detroit Lions'],
    'green-bay-packers': ['GB', 'Green Bay', 'Packers', 'Green Bay Packers'],
    'houston-texans': ['HOU', 'Houston', 'Texans', 'Houston Texans'],
    'indianapolis-colts': ['IND', 'Indianapolis', 'Colts', 'Indianapolis Colts'],
    'jacksonville-jaguars': ['JAX', 'Jacksonville', 'Jaguars', 'Jacksonville Jaguars'],
    'kansas-city-chiefs': ['KC', 'Kansas City', 'Chiefs', 'Kansas City Chiefs'],
    'las-vegas-raiders': ['LV', 'Las Vegas', 'Raiders', 'Las Vegas Raiders'],
    'los-angeles-chargers': ['LAC', 'LA Chargers', 'Chargers', 'Los Angeles Chargers'],
    'los-angeles-rams': ['LAR', 'LA Rams', 'Rams', 'Los Angeles Rams'],
    'miami-dolphins': ['MIA', 'Miami', 'Dolphins', 'Miami Dolphins'],
    'minnesota-vikings': ['MIN', 'Minnesota', 'Vikings', 'Minnesota Vikings'],
    'new-england-patriots': ['NE', 'New England', 'Patriots', 'New England Patriots'],
    'new-orleans-saints': ['NO', 'New Orleans', 'Saints', 'New Orleans Saints'],
    'new-york-giants': ['NYG', 'NY Giants', 'Giants', 'New York Giants'],
    'new-york-jets': ['NYJ', 'NY Jets', 'Jets', 'New York Jets'],
    'philadelphia-eagles': ['PHI', 'Philadelphia', 'Eagles', 'Philadelphia Eagles'],
    'pittsburgh-steelers': ['PIT', 'Pittsburgh', 'Steelers', 'Pittsburgh Steelers'],
    'san-francisco-49ers': ['SF', 'San Francisco', '49ers', 'San Francisco 49ers'],
    'seattle-seahawks': ['SEA', 'Seattle', 'Seahawks', 'Seattle Seahawks'],
    'tampa-bay-buccaneers': ['TB', 'Tampa Bay', 'Buccaneers', 'Tampa Bay Buccaneers'],
    'tennessee-titans': ['TEN', 'Tennessee', 'Titans', 'Tennessee Titans'],
    'washington-commanders': ['WAS', 'Washington', 'Commanders', 'Washington Commanders'],
}

NBA_ALIASES = {
    'atlanta-hawks': ['ATL', 'Atlanta', 'Hawks', 'Atlanta Hawks'],
    'boston-celtics': ['BOS', 'Boston', 'Celtics', 'Boston Celtics'],
    'brooklyn-nets': ['BKN', 'Brooklyn', 'Nets', 'Brooklyn Nets'],
    'charlotte-hornets': ['CHA', 'Charlotte', 'Hornets', 'Charlotte Hornets'],
    'chicago-bulls': ['CHI', 'Chicago', 'Bulls', 'Chicago Bulls'],
    'cleveland-cavaliers': ['CLE', 'Cleveland', 'Cavaliers', 'Cleveland Cavaliers'],
    'dallas-mavericks': ['DAL', 'Dallas', 'Mavericks', 'Dallas Mavericks'],
    'denver-nuggets': ['DEN', 'Denver', 'Nuggets', 'Denver Nuggets'],
    'detroit-pistons': ['DET', 'Detroit', 'Pistons', 'Detroit Pistons'],
    'golden-state-warriors': ['GSW', 'Golden State', 'Warriors', 'Golden State Warriors'],
    'houston-rockets': ['HOU', 'Houston', 'Rockets', 'Houston Rockets'],
    'indiana-pacers': ['IND', 'Indiana', 'Pacers', 'Indiana Pacers'],
    'los-angeles-clippers': ['LAC', 'LA Clippers', 'Clippers', 'Los Angeles Clippers'],
    'los-angeles-lakers': ['LAL', 'LA Lakers', 'Lakers', 'Los Angeles Lakers'],
    'memphis-grizzlies': ['MEM', 'Memphis', 'Grizzlies', 'Memphis Grizzlies'],
    'miami-heat': ['MIA', 'Miami', 'Heat', 'Miami Heat'],
    'milwaukee-bucks': ['MIL', 'Milwaukee', 'Bucks', 'Milwaukee Bucks'],
    'minnesota-timberwolves': ['MIN', 'Minnesota', 'Timberwolves', 'Minnesota Timberwolves'],
    'new-orleans-pelicans': ['NOP', 'New Orleans', 'Pelicans', 'New Orleans Pelicans'],
    'new-york-knicks': ['NYK', 'NY Knicks', 'Knicks', 'New York Knicks'],
    'oklahoma-city-thunder': ['OKC', 'Oklahoma City', 'Thunder', 'Oklahoma City Thunder'],
    'orlando-magic': ['ORL', 'Orlando', 'Magic', 'Orlando Magic'],
    'philadelphia-76ers': ['PHI', 'Philadelphia', '76ers', 'Philadelphia 76ers'],
    'phoenix-suns': ['PHX', 'Phoenix', 'Suns', 'Phoenix Suns'],
    'portland-trail-blazers': ['POR', 'Portland', 'Trail Blazers', 'Portland Trail Blazers'],
    'sacramento-kings': ['SAC', 'Sacramento', 'Kings', 'Sacramento Kings'],
    'san-antonio-spurs': ['SAS', 'San Antonio', 'Spurs', 'San Antonio Spurs'],
    'toronto-raptors': ['TOR', 'Toronto', 'Raptors', 'Toronto Raptors'],
    'utah-jazz': ['UTA', 'Utah', 'Jazz', 'Utah Jazz'],
    'washington-wizards': ['WAS', 'Washington', 'Wizards', 'Washington Wizards'],
}

MLB_ALIASES = {
    'arizona-diamondbacks': ['ARI', 'Arizona', 'Diamondbacks', 'Arizona Diamondbacks'],
    'atlanta-braves': ['ATL', 'Atlanta', 'Braves', 'Atlanta Braves'],
    'baltimore-orioles': ['BAL', 'Baltimore', 'Orioles', 'Baltimore Orioles'],
    'boston-red-sox': ['BOS', 'Boston', 'Red Sox', 'Boston Red Sox'],
    'chicago-cubs': ['CHC', 'Chicago Cubs', 'Cubs'],
    'chicago-white-sox': ['CWS', 'Chicago White Sox', 'White Sox', 'Chi White Sox'],
    'cincinnati-reds': ['CIN', 'Cincinnati', 'Reds', 'Cincinnati Reds'],
    'cleveland-guardians': ['CLE', 'Cleveland', 'Guardians', 'Cleveland Guardians'],
    'colorado-rockies': ['COL', 'Colorado', 'Rockies', 'Colorado Rockies'],
    'detroit-tigers': ['DET', 'Detroit', 'Tigers', 'Detroit Tigers'],
    'houston-astros': ['HOU', 'Houston', 'Astros', 'Houston Astros'],
    'kansas-city-royals': ['KC', 'Kansas City', 'Royals', 'Kansas City Royals'],
    'los-angeles-angels': ['LAA', 'LA Angels', 'Angels', 'Los Angeles Angels', 'Los Angeles Angels of Anaheim'],
    'los-angeles-dodgers': ['LAD', 'LA Dodgers', 'Dodgers', 'Los Angeles Dodgers'],
    'miami-marlins': ['MIA', 'Miami', 'Marlins', 'Miami Marlins', 'Florida Marlins'],
    'milwaukee-brewers': ['MIL', 'Milwaukee', 'Brewers', 'Milwaukee Brewers'],
    'minnesota-twins': ['MIN', 'Minnesota', 'Twins', 'Minnesota Twins'],
    'new-york-mets': ['NYM', 'NY Mets', 'Mets', 'New York Mets'],
    'new-york-yankees': ['NYY', 'NY Yankees', 'Yankees', 'New York Yankees'],
    'oakland-athletics': ['OAK', 'Oakland', 'Athletics', 'Oakland A\'s', 'A\'s', 'Oakland Athletics'],
    'philadelphia-phillies': ['PHI', 'Philadelphia', 'Phillies', 'Philadelphia Phillies'],
    'pittsburgh-pirates': ['PIT', 'Pittsburgh', 'Pirates', 'Pittsburgh Pirates'],
    'san-diego-padres': ['SD', 'San Diego', 'Padres', 'San Diego Padres'],
    'san-francisco-giants': ['SF', 'San Francisco', 'Giants', 'San Francisco Giants'],
    'seattle-mariners': ['SEA', 'Seattle', 'Mariners', 'Seattle Mariners'],
    'st-louis-cardinals': ['STL', 'St. Louis', 'Cardinals', 'St. Louis Cardinals'],
    'tampa-bay-rays': ['TB', 'Tampa Bay', 'Rays', 'Tampa Bay Rays', 'Tampa Rays'],
    'texas-rangers': ['TEX', 'Texas', 'Rangers', 'Texas Rangers'],
    'toronto-blue-jays': ['TOR', 'Toronto', 'Blue Jays', 'Toronto Blue Jays'],
    'washington-nationals': ['WSH', 'Washington', 'Nationals', 'Washington Nationals', 'Nats']
}

NHL_ALIASES = {
    'anaheim-ducks': ['ANA', 'Anaheim', 'Ducks', 'Anaheim Ducks'],
    'arizona-coyotes': ['ARI', 'Arizona', 'Coyotes', 'Arizona Coyotes'],
    'boston-bruins': ['BOS', 'Boston', 'Bruins', 'Boston Bruins'],
    'buffalo-sabres': ['BUF', 'Buffalo', 'Sabres', 'Buffalo Sabres'],
    'calgary-flames': ['CGY', 'Calgary', 'Flames', 'Calgary Flames'],
    'carolina-hurricanes': ['CAR', 'Carolina', 'Hurricanes', 'Carolina Hurricanes', 'Canes'],
    'chicago-blackhawks': ['CHI', 'Chicago', 'Blackhawks', 'Chicago Blackhawks'],
    'colorado-avalanche': ['COL', 'Colorado', 'Avalanche', 'Colorado Avalanche'],
    'columbus-blue-jackets': ['CBJ', 'Columbus', 'Blue Jackets', 'Columbus Blue Jackets'],
    'dallas-stars': ['DAL', 'Dallas', 'Stars', 'Dallas Stars'],
    'detroit-red-wings': ['DET', 'Detroit', 'Red Wings', 'Detroit Red Wings'],
    'edmonton-oilers': ['EDM', 'Edmonton', 'Oilers', 'Edmonton Oilers'],
    'florida-panthers': ['FLA', 'Florida', 'Panthers', 'Florida Panthers'],
    'los-angeles-kings': ['LAK', 'LA Kings', 'Kings', 'Los Angeles Kings'],
    'minnesota-wild': ['MIN', 'Minnesota', 'Wild', 'Minnesota Wild'],
    'montreal-canadiens': ['MTL', 'Montreal', 'Canadiens', 'Montreal Canadiens', 'Habs'],
    'nashville-predators': ['NSH', 'Nashville', 'Predators', 'Nashville Predators', 'Preds'],
    'new-jersey-devils': ['NJD', 'New Jersey', 'Devils', 'New Jersey Devils'],
    'new-york-islanders': ['NYI', 'NY Islanders', 'Islanders', 'New York Islanders'],
    'new-york-rangers': ['NYR', 'NY Rangers', 'Rangers', 'New York Rangers'],
    'ottawa-senators': ['OTT', 'Ottawa', 'Senators', 'Ottawa Senators', 'Sens'],
    'philadelphia-flyers': ['PHI', 'Philadelphia', 'Flyers', 'Philadelphia Flyers'],
    'pittsburgh-penguins': ['PIT', 'Pittsburgh', 'Penguins', 'Pittsburgh Penguins', 'Pens'],
    'san-jose-sharks': ['SJS', 'San Jose', 'Sharks', 'San Jose Sharks'],
    'seattle-kraken': ['SEA', 'Seattle', 'Kraken', 'Seattle Kraken'],
    'st-louis-blues': ['STL', 'St. Louis', 'Blues', 'St. Louis Blues'],
    'tampa-bay-lightning': ['TBL', 'Tampa Bay', 'Lightning', 'Tampa Bay Lightning', 'Bolts'],
    'toronto-maple-leafs': ['TOR', 'Toronto', 'Maple Leafs', 'Toronto Maple Leafs', 'Leafs'],
    'vancouver-canucks': ['VAN', 'Vancouver', 'Canucks', 'Vancouver Canucks'],
    'vegas-golden-knights': ['VGK', 'Vegas', 'Golden Knights', 'Vegas Golden Knights', 'Knights'],
    'washington-capitals': ['WSH', 'Washington', 'Capitals', 'Washington Capitals', 'Caps'],
    'winnipeg-jets': ['WPG', 'Winnipeg', 'Jets', 'Winnipeg Jets'],
}

MLS_ALIASES = {
    'atlanta-united': ['ATL', 'Atlanta', 'Atlanta United', 'Atlanta United FC', 'United'],
    'austin-fc': ['ATX', 'Austin', 'Austin FC'],
    'cf-montreal': ['MTL', 'Montreal', 'CF Montréal', 'Club de Foot Montreal', 'CF Montreal'],
    'charlotte-fc': ['CLT', 'Charlotte', 'Charlotte FC'],
    'chicago-fire': ['CHI', 'Chicago', 'Chicago Fire', 'Chicago Fire FC', 'Fire'],
    'fc-cincinnati': ['CIN', 'Cincinnati', 'FC Cincinnati', 'FCC'],
    'colorado-rapids': ['COL', 'Colorado', 'Colorado Rapids', 'Rapids'],
    'columbus-crew': ['CLB', 'Columbus', 'Columbus Crew', 'Columbus Crew SC', 'The Crew'],
    'dc-united': ['DC', 'D.C. United', 'DC United', 'D.C.', 'Washington DC'],
    'fc-dallas': ['DAL', 'Dallas', 'FC Dallas'],
    'houston-dynamo': ['HOU', 'Houston', 'Houston Dynamo', 'Houston Dynamo FC', 'Dynamo'],
    'inter-miami': ['MIA', 'Miami', 'Inter Miami', 'Inter Miami CF', 'Club Internacional de Fútbol Miami'],
    'la-galaxy': ['LA', 'LA Galaxy', 'Los Angeles Galaxy', 'Galaxy'],
    'los-angeles-fc': ['LAFC', 'LA FC', 'Los Angeles FC', 'LA Football Club', 'Los Angeles'],
    'minnesota-united': ['MIN', 'Minnesota', 'Minnesota United', 'Minnesota United FC', 'Loons'],
    'nashville-sc': ['NSH', 'Nashville', 'Nashville SC', 'Nashville Soccer Club'],
    'ne-revolution': ['NE', 'New England', 'New England Revolution', 'Revs'],
    'new-york-city-fc': ['NYC', 'NYCFC', 'New York City FC', 'New York City', 'City'],
    'new-york-red-bulls': ['NY', 'NYRB', 'New York Red Bulls', 'Red Bulls'],
    'orlando-city': ['ORL', 'Orlando', 'Orlando City', 'Orlando City SC'],
    'philadelphia-union': ['PHI', 'Philadelphia', 'Philadelphia Union', 'Union'],
    'portland-timbers': ['POR', 'Portland', 'Portland Timbers', 'Timbers'],
    'real-salt-lake': ['RSL', 'Salt Lake', 'Real Salt Lake', 'RSL FC'],
    'san-jose-earthquakes': ['SJ', 'San Jose', 'San Jose Earthquakes', 'Earthquakes', 'Quakes'],
    'seattle-sounders': ['SEA', 'Seattle', 'Seattle Sounders', 'Seattle Sounders FC', 'Sounders'],
    'sporting-kansas-city': ['SKC', 'Kansas City', 'Sporting KC', 'Sporting Kansas City', 'Sporting'],
    'st-louis-city': ['STL', 'St. Louis', 'St. Louis City', 'St. Louis City SC', 'CITY SC'],
    'toronto-fc': ['TOR', 'Toronto', 'Toronto FC', 'TFC'],
    'vancouver-whitecaps': ['VAN', 'Vancouver', 'Vancouver Whitecaps', 'Whitecaps', 'Whitecaps FC'],
}

NCAA_ALIASES = {
    # Big Ten Conference
    'illinois-fighting-illini': ['ILL', 'Illinois', 'Fighting Illini'],
    'indiana-hoosiers': ['IND', 'Indiana', 'Hoosiers'],
    'iowa-hawkeyes': ['IOWA', 'Iowa', 'Hawkeyes'],
    'maryland-terrapins': ['MD', 'Maryland', 'Terrapins', 'Terps'],
    'michigan-wolverines': ['MICH', 'Michigan', 'Wolverines'],
    'michigan-state-spartans': ['MSU', 'Michigan State', 'Spartans'],
    'minnesota-golden-gophers': ['MINN', 'Minnesota', 'Golden Gophers', 'Gophers'],
    'nebraska-cornhuskers': ['NEB', 'Nebraska', 'Cornhuskers', 'Huskers'],
    'northwestern-wildcats': ['NU', 'Northwestern', 'Wildcats'],
    'ohio-state-buckeyes': ['OSU', 'Ohio State', 'Buckeyes'],
    'oregon-ducks': ['ORE', 'Oregon', 'Ducks'],
    'penn-state-nittany-lions': ['PSU', 'Penn State', 'Nittany Lions'],
    'purdue-boilermakers': ['PUR', 'Purdue', 'Boilermakers'],
    'rutgers-scarlet-knights': ['RUT', 'Rutgers', 'Scarlet Knights'],
    'ucla-bruins': ['UCLA', 'UCLA', 'Bruins'],
    'usc-trojans': ['USC', 'USC', 'Trojans'],
    'washington-huskies': ['UW', 'Washington', 'Huskies'],
    'wisconsin-badgers': ['WIS', 'Wisconsin', 'Badgers'],

    # Big 12 Conference
    'arizona-wildcats': ['ARIZ', 'Arizona', 'Wildcats'],
    'arizona-state-sun-devils': ['ASU', 'Arizona State', 'Sun Devils'],
    'baylor-bears': ['BU', 'Baylor', 'Bears'],
    'byu-cougars': ['BYU', 'BYU', 'Cougars'],
    'cincinnati-bearcats': ['CIN', 'Cincinnati', 'Bearcats'],
    'colorado-buffaloes': ['COLO', 'Colorado', 'Buffaloes', 'Buffs'],
    'houston-cougars': ['UH', 'Houston', 'Cougars'],
    'iowa-state-cyclones': ['ISU', 'Iowa State', 'Cyclones'],
    'kansas-jayhawks': ['KU', 'Kansas', 'Jayhawks'],
    'kansas-state-wildcats': ['KSU', 'Kansas State', 'Wildcats'],
    'oklahoma-state-cowboys': ['OKST', 'Oklahoma State', 'Cowboys', 'Pokes'],
    'tcu-horned-frogs': ['TCU', 'TCU', 'Horned Frogs'],
    'texas-tech-red-raiders': ['TTU', 'Texas Tech', 'Red Raiders'],
    'ucf-knights': ['UCF', 'UCF', 'Knights'],
    'utah-utes': ['UTAH', 'Utah', 'Utes'],
    'west-virginia-mountaineers': ['WVU', 'West Virginia', 'Mountaineers'],

    # Southeastern Conference (SEC)
    'alabama-crimson-tide': ['ALA', 'Alabama', 'Crimson Tide'],
    'arkansas-razorbacks': ['ARK', 'Arkansas', 'Razorbacks', 'Hogs'],
    'auburn-tigers': ['AUB', 'Auburn', 'Tigers'],
    'florida-gators': ['UF', 'Florida', 'Gators'],
    'georgia-bulldogs': ['UGA', 'Georgia', 'Bulldogs', 'Dawgs'],
    'kentucky-wildcats': ['UK', 'Kentucky', 'Wildcats'],
    'lsu-tigers': ['LSU', 'LSU', 'Tigers'],
    'mississippi-rebels': ['MISS', 'Ole Miss', 'Rebels'],
    'mississippi-state-bulldogs': ['MSST', 'Mississippi State', 'Bulldogs'],
    'missouri-tigers': ['MIZZ', 'Missouri', 'Tigers'],
    'oklahoma-sooners': ['OU', 'Oklahoma', 'Sooners'],
    'south-carolina-gamecocks': ['SCAR', 'South Carolina', 'Gamecocks'],
    'tennessee-volunteers': ['TENN', 'Tennessee', 'Volunteers', 'Vols'],
    'texas-longhorns': ['TEX', 'Texas', 'Longhorns'],
    'texas-am-aggies': ['TAMU', 'Texas A&M', 'Aggies'],
    'vanderbilt-commodores': ['VAN', 'Vanderbilt', 'Commodores', 'Dores'],

    # Atlantic Coast Conference (ACC)
    'boston-college-eagles': ['BC', 'Boston College', 'Eagles'],
    'california-golden-bears': ['CAL', 'California', 'Golden Bears', 'Cal'],
    'clemson-tigers': ['CLEM', 'Clemson', 'Tigers'],
    'duke-blue-devils': ['DUKE', 'Duke', 'Blue Devils'],
    'florida-state-seminoles': ['FSU', 'Florida State', 'Seminoles', 'Noles'],
    'georgia-tech-yellow-jackets': ['GT', 'Georgia Tech', 'Yellow Jackets'],
    'louisville-cardinals': ['LOU', 'Louisville', 'Cardinals'],
    'miami-hurricanes': ['MIA', 'Miami', 'Hurricanes', 'Canes'],
    'north-carolina-tar-heels': ['UNC', 'North Carolina', 'Tar Heels'],
    'nc-state-wolfpack': ['NCST', 'NC State', 'Wolfpack'],
    'notre-dame-fighting-irish': ['ND', 'Notre Dame', 'Fighting Irish'],
    'pittsburgh-panthers': ['PITT', 'Pittsburgh', 'Panthers'],
    'smu-mustangs': ['SMU', 'SMU', 'Mustangs'],
    'stanford-cardinal': ['STAN', 'Stanford', 'Cardinal'],
    'syracuse-orange': ['SYR', 'Syracuse', 'Orange'],
    'virginia-cavaliers': ['UVA', 'Virginia', 'Cavaliers', 'Wahoos'],
    'virginia-tech-hokies': ['VT', 'Virginia Tech', 'Hokies'],
    'wake-forest-demon-deacons': ['WF', 'Wake Forest', 'Demon Deacons', 'Deacs'],

    # Pac-12 Conference (2025 Members)
    'oregon-state-beavers': ['OSU', 'Oregon State', 'Beavers'],
    'washington-state-cougars': ['WSU', 'Washington State', 'Cougars'],
}

LEAGUE_ALIASES = {
    'nfl': NFL_ALIASES, 
    'nba': NBA_ALIASES,
    'mlb': MLB_ALIASES,
    'mls': MLS_ALIASES,
    'nhl': NHL_ALIASES,
    'ncaaf': NCAA_ALIASES,
    'ncaab': NCAA_ALIASES,
    'ncaaw': NCAA_ALIASES,
}